### ISSUE TITLE
WebSocket API call timeout

### ISSUE THREAD

**Issue by Katou-Kouseki** [Nao-desu/drift_bottle#1]
捡到一个破碎的瓶子,里面的东西早已被海水腐蚀，无法辨认
(WebSocket API call timeout)

后台报错：ApiRejection { code: -2, message: 'packet timeout (2781)' }

这种一般是什么情况，是通过云崽ws接的hoshino

**Comment by Nao-desu** [comment]
如果发送的是这条消息，说明漂流瓶的信息已经获取到，但是发送的过程出了问题，你的问题应该和插件没有关系

[oicq](https://github.com/takayama-lily/oicq)/[icqq](https://github.com/icqqjs/icqq)的报错和我用的gocq不一样，尝试去那边提交issue
