### ISSUE TITLE
关于违规的漂流瓶

### ISSUE THREAD

**Issue by yuyue31** [Nao-desu/drift_bottle#2]
请问大佬有没有相关代码是删除一些违规的漂流瓶的，还是说直接从json里面删除就可以了，谢谢大佬

**Comment by Nao-desu** [comment]
没有写这方面的，有空可能会弄，直接删除json中的任意一项会导致写入顺序出问题，只可以修改内容

**Comment by yuyue31** [comment]
关于图片，如果是图片违规是否可以直接删除图片文件夹里的图片呢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月25日(周二) 晚上7:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Nao-desu/drift_bottle] 关于违规的漂流瓶 (Issue #2)




 
没有写这方面的，有空可能会弄，直接删除json中的任意一项会导致写入顺序出问题，只可以修改内容

**Comment by Nao-desu** [comment]
你可以删除json内记录消息中对应图片cq码那一段，只删掉图片的话会把cq码原样发出

**Comment by Nao-desu** [comment]
已解决，请更新插件
